models:
  - name: "gpt-3.5-turbo"
    type: "ChatOpenAI"
    model_name: "gpt-3.5-turbo"
    temperature: 0.3
  - name: "gpt-4"
    type: "ChatOpenAI"
    model_name: "gpt-4"



embeddings:
  - name: "openai-embedding"
    type: "OpenAIEmbeddings"
    vb_name: "openai-faiss"
  - name: "hf-sentence-transformer"
    type: "HuggingFaceEmbeddings"
    vb_name: "hf-faiss"
    model_name: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
  - name: "dragon"
    type: "DragonPlusEmbeddings"
    vb_name: "dragon-faiss"
  - name: "dpr"
    type: "DPREmbeddings"
    vb_name: "dpr-faiss"


vectordb:
  - vb_name: "hf-faiss"
    path: /mnt/c/Users/kur0/webscrap/autoscrapergpt/qa_bot_test/hf_all.faiss
  - vb_name: "openai-faiss"
    path: /mnt/c/Users/kur0/webscrap/autoscrapergpt/qa_bot_test/openai_all.faiss
  - vb_name: "dragon-faiss"
    path: /mnt/c/Users/kur0/webscrap/autoscrapergpt/qa_bot_test/dragon_524.faiss
  - vb_name: "dpr-faiss"
    path: /mnt/c/Users/kur0/webscrap/autoscrapergpt/qa_bot_test/dpr_524.faiss
